version: '3.4'

services:
  waproject.webapi:
    image: ${DOCKER_REGISTRY-}waprojectwebapi
    build:
      context: .
      dockerfile: src/presentation/waproject.WebApi/Dockerfile
    depends_on:
      - mssql
      - seq

  seq:    
    image: datalust/seq    
    ports:
      - '8005:80'      
    environment:
      - ACCEPT_EULA=Y 
  
  mssql:
    build:
      context: .
      dockerfile: mssql/mssql.Dockerfile
    restart: always
    ports:
      - "1440:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_01